### ISSUE TITLE
Prevent dependabot from updating scalatest_2.13

### ISSUE THREAD

**Issue by ckittl** [ie3-institute/powerFactory2psdm#24]
https://github.com/ie3-institute/powerFactory2psdm/blob/d3b52881a421cf2cb427cb37700c40eac04d32be/build.gradle#L73

Dependabot works as intended, as it updates to the most recent version. However, within maven central, there is a version `3.3.0-SNAP3`, which actually isn't the most recent version (and also a snapshot). Maybe you would like to take a look on [how to configure dependabot](https://dependabot.com/docs/config-file/#ignored_updates) and exclude this version.

Moreover, there is also the opportunity to assign default reviewers and stuff. If you figure out a reasonable yaml-config, this could be a blueprint for our other projects as well.

**Comment by t-ober** [comment]
As a little note : We now use the native github version of `dependabot` instead of `dependabot preview`.

@ckittl 

Best case would be to exclude every version that contains "-SNAP". The problem is, that `*` wildcard pattern matching doesn't work for Versions. We can denote every version 3 by specifying `3.x` but I guess `x.-SNAP` will not do the trick. 

I could  go for `3.3.x` to exclude the currently available snapshots and delete it once a stable `3.3.0` is out, or go for `versions: [3.3.0-SNAP1, 3.3.0-SNAP2, 3.3.0-SNAP3]` which would mean i have to update it manually when a `SNAP4` surfaces.

Any preferences or do I miss something?

**Comment by ckittl** [comment]
You may add version "wildcards" as usually used within the dependency management. Therefore, I introduced the ignorance of `x.x.x-SNAP+` and `x.x.x-M+`. However, I'm not totally sure, if this blocks more versions, that I would like to. We have to keep an eye on this.
